\# LEGAL TERMS
\# ===========
\# This documentation is released to the public domain.
\#
\# GROFF SYNTAX
\# ============
\# Italics for files and important words, bold for programs and arguments.
\#
.
.ds timestamp 2022-04-29
.\" Update the above date whenever this file is updated.
.
.TH PIC2IMG 1 \*[timestamp] "pic2img v\*[timestamp]"
.SH NAME
pic2img \- convert a PIC diagram into a cropped image
.
.
.\" ====================================================================
.SH SYNOPSIS
.\" ====================================================================
.
.SY pic2img
.OP OPTIONS ...
.OP CONVERT-ARGUMENTS ...
.RI \< in " \>" out
.YS
.
.SY pic2img
.OP \-\-help
.OP \-\-version
.YS
.
.
.\" ====================================================================
.SH DESCRIPTION
.\" ====================================================================
.
.B pic2img
reads a
.BR gpic (1)
program from the standard input and writes an image file,
by default in Portable Network Graphics (PNG) format,
to the standard output.
.
It furthermore translates
.BR geqn (1)
constructs, so it can be used for generating images of mathematical
formulae. The 
.BR preconv (1)
preprocessor can also be enabled to parse non-English text.
.
.PP
The input PIC code should
.I not
be wrapped with the
.B \&.PS
and
.B \&.PE
macros that normally guard it within
.BR groff (1)
documents.
.
.PP
Please note that
.B pic2img
takes its input
.IR "from the standard input" ,
and 
.IR "writes to standard output" .
It does not feed from an input file or write to an output file directly.
You can use shell stream redirections (\fB\<\fR and \fB\>\fR) 
to control input and output to files.
.IP
$
.B pic2img
.RI < infile.pic " >" outfile.png
.br
.
.
.\" FIXME: How old?  This text hasn't been touched since 2008 at latest.
.\" Older versions of
.\" .I \%convert
.\" will produce a black-on-white graphic; newer ones may produce a
.\" black-on-transparent graphic.
.
.PP
Arguments not recognized by
.B pic2img
are passed to the ImageMagick program
.BR \%convert (1).
.
By specifying these, you can give your image a border,
set the image's pixel density,
or perform other useful transformations.
.
.
.PP
The output image is clipped using
.BR \%convert 's
.B \-trim
option to the smallest possible bounding box.
.
.
.\" ====================================================================
.SH OPTIONS
.\" ====================================================================
.
.
.TP
.BI \-f " format"
.TQ
.BI \-\-format " format"
Write the image in
.IR format ,
which must be understood by
.BR \%convert ;
the default is PNG.
.
.
.TP
.BI "\-q " quality
.TQ
.BI "\-\-quality " quality
Sets the output image quality, on a 1\(en3 scale (1 being the lowest quality).
The
.IR 1 ", " 2 " and " 3
values correspond to 
.BR \%convert \'s
.B -density
values of
.IR 300 ", " 600 " and " 900 
respectively, which applies to reading the input PostScript from
.BR groff .
If out of this scale, the
.I quality
value is directly mapped to the
.B -density
option.
.
.
.TP
.BI \-s " size"
Set size of the output image, according to 
.BR convert (1)'s
.B -geometry
syntax.
.
.
.TP
.B \-b
Set a white background to the output image, even when outputting to PNG 
.IR format .
.
.
.TP
.B \-k
Enable 
.BR groff 's
.BR preconv
preprocessor to parse the input.
.
.
.TP
.BI \-K " preconv-encoding"
Set
.BR groff 's
.BR preconv
preprocessor
input encoding. Implies
.BR \-k .
.
.
.TP
.BI \-\-eqn " delimiters"
Use
.I delimiters
as the opening and closing
characters that delimit
.B geqn
directives;
the default is \(lq$$\(rq.
The option argument
.I delimiters
should be a two-character string,
but an empty string (\(dq\(dq) is accepted as a directive to disable
.B geqn
processing.
.
.
.TP
.B \-U
.TQ
.B \-\-unsafe
Run
.B groff
in unsafe mode, enabling the PIC command
.B sh
to execute arbitrary Unix shell commands.
The
.BR groff (1)
default is to forbid this.
.
.
.TP
.B \-v
.TQ
.B \-\-version
Display version information and exit.
.
.
.TP
.B \-h
.TQ
.B \-\-help
Display a usage message and exit.
.
.
.\" ====================================================================
.SH "EXAMPLES"
.\" ====================================================================
.
This command creates a crisp
.I pic.jpg
JPG file of 1920 pixel of width reading the pic instructions of the
.I diagram.pic
file, with
.BR groff 's
unsafe mode and the
.B preconv
preprocessor enabled.
.IP
.RB "$ " pic2img
-b -k -U -f jpg -s 1920x -q 3
.RI < diagram.pic " >" pic.jpg
.
.
.\" ====================================================================
.SH AUTHORS
.\" ====================================================================
.
.I pic2img
was written by
.MT mail@\:sylsau.com
Sylvain Saubier
.ME ,
based on a recipe by Eric S. \& Raymonds.
.
.
.\" ====================================================================
.SH "SEE ALSO"
.\" ====================================================================
.
.PP
W.\& Richard Stevens,
.UR http://\:www.kohala.com/\:start/\:troff/\:pic2html.html
.I Turning PIC into HTML
.UE
.
.PP
ImageMagick's online manual,
.UR https://imagemagick.org/script/command-line-processing.php#geometry
.I Anatomy of the Command-line / Image Geometry
.UE
.
.PP
ImageMagick's online manual,
.UR https://imagemagick.org/script/command-line-options.php#density
.I Annotated List of Command-line Options / -density
.UE
.
.PP
.BR groff (1),
.BR \%convert (1),
.BR gpic (1),
.BR geqn (1),
.BR preconv (1),
.BR eqn2graph (1),
.BR grap2graph (1)
.
.\" Local Variables:
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff:
